services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${AI_SERVICE_PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-demo}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - API_FRONTEND_ORIGIN=${API_FRONTEND_ORIGIN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-500}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.3}
      - OPENAI_API_URL=${OPENAI_API_URL}
      - DEMO_MODE=${DEMO_MODE:-true}
      - DEMO_MOCK_AI=${DEMO_MOCK_AI:-false}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10MB}
      - SUPPORTED_FILE_TYPES=${SUPPORTED_FILE_TYPES}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - JAVA_OPTS=-Xmx1024m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-4200}:80"
    environment:
      - API_BACKEND_URL=${API_FRONTEND_ORIGIN}
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
